//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeTests.Resources.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example1.
        /// </summary>
        public static string D00_E1 {
            get {
                return ResourceManager.GetString("D00_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example2.
        /// </summary>
        public static string D00_E2 {
            get {
                return ResourceManager.GetString("D00_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Puzzle.
        /// </summary>
        public static string D00_Puzzle {
            get {
                return ResourceManager.GetString("D00_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54172
        ///58469
        ///92948
        ///143402
        ///57563
        ///54532
        ///68042
        ///89847
        ///70872
        ///54069
        ///107310
        ///146439
        ///88851
        ///142869
        ///71309
        ///89613
        ///70338
        ///87708
        ///95305
        ///134384
        ///128250
        ///134991
        ///91270
        ///127819
        ///68650
        ///102556
        ///129882
        ///68688
        ///129939
        ///137344
        ///102624
        ///90828
        ///86487
        ///91712
        ///114866
        ///75697
        ///107599
        ///99053
        ///87511
        ///128128
        ///57772
        ///69314
        ///90771
        ///145376
        ///100730
        ///142675
        ///112731
        ///83985
        ///123565
        ///127325
        ///86597
        ///121772
        ///131992
        ///148859
        ///93348
        ///77294
        ///119763
        ///74636
        ///95592
        ///79628
        ///78861
        ///68565
        ///88820
        ///134291
        ///69262
        ///128678
        ///118216
        ///52799
        ///92731
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D01_Puzzle {
            get {
                return ResourceManager.GetString("D01_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,0,0,3,1,1,2,3,1,3,4,3,1,5,0,3,2,13,1,19,1,9,19,23,2,23,13,27,1,27,9,31,2,31,6,35,1,5,35,39,1,10,39,43,2,43,6,47,1,10,47,51,2,6,51,55,1,5,55,59,1,59,9,63,1,13,63,67,2,6,67,71,1,5,71,75,2,6,75,79,2,79,6,83,1,13,83,87,1,9,87,91,1,9,91,95,1,5,95,99,1,5,99,103,2,13,103,107,1,6,107,111,1,9,111,115,2,6,115,119,1,13,119,123,1,123,6,127,1,127,5,131,2,10,131,135,2,135,10,139,1,13,139,143,1,10,143,147,1,2,147,151,1,6,151,0,99,2,14,0,0.
        /// </summary>
        public static string D02_Puzzle {
            get {
                return ResourceManager.GetString("D02_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R991,U77,L916,D26,R424,D739,L558,D439,R636,U616,L364,D653,R546,U909,L66,D472,R341,U906,L37,D360,L369,D451,L649,D521,R2,U491,R409,U801,R23,U323,L209,U171,L849,D891,L854,U224,R476,D519,L937,U345,R722,D785,L312,D949,R124,U20,R677,D236,R820,D320,L549,D631,R42,U621,R760,U958,L925,U84,R914,U656,R598,D610,R397,D753,L109,U988,R435,U828,R219,U583,L317,D520,L940,D850,R594,D801,L422,U292,R883,U204,L76,U860,L753,U483,L183,U179,R441,U163,L859,U437,L485,D239,R454,D940,R689,D704,R110,D12,R370,D413,L192,D979,R990,D651,L308 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D03_Puzzle {
            get {
                return ResourceManager.GetString("D03_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 124075-580769.
        /// </summary>
        public static string D04_Puzzle {
            get {
                return ResourceManager.GetString("D04_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,225,1,225,6,6,1100,1,238,225,104,0,1102,31,68,225,1001,13,87,224,1001,224,-118,224,4,224,102,8,223,223,1001,224,7,224,1,223,224,223,1,174,110,224,1001,224,-46,224,4,224,102,8,223,223,101,2,224,224,1,223,224,223,1101,13,60,224,101,-73,224,224,4,224,102,8,223,223,101,6,224,224,1,224,223,223,1101,87,72,225,101,47,84,224,101,-119,224,224,4,224,1002,223,8,223,1001,224,6,224,1,223,224,223,1101,76,31,225,1102,60,43,225,1102,45,31,225,1102,63,9,225,2,170,122,224,1001,224,-486,224,4,224,102,8,223,223,101,2,224,224 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D05_Puzzle {
            get {
                return ResourceManager.GetString("D05_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S5F)4L5
        ///7BP)2V1
        ///DHC)KGY
        ///JZG)PN7
        ///RV4)123
        ///2DJ)LPW
        ///19G)31B
        ///H4Z)TC6
        ///3YP)XTQ
        ///H9Q)QXJ
        ///R77)3FM
        ///JD3)GXY
        ///3WS)YHL
        ///X9K)BWP
        ///656)7PW
        ///9S2)LGY
        ///CZB)VXR
        ///1YS)Y5H
        ///1XY)L9Y
        ///NH1)YW5
        ///HVD)2PS
        ///Y1C)4SY
        ///LKH)1PV
        ///7HZ)GZD
        ///TJZ)WV7
        ///V8K)Z28
        ///DB4)S1Q
        ///TRV)4TM
        ///3L3)6YN
        ///LD1)4PR
        ///1XP)3YF
        ///B6Q)QRX
        ///QSL)JV7
        ///MFC)QSJ
        ///TC2)9JZ
        ///PLS)2TK
        ///T6Y)DNB
        ///HDT)BY7
        ///44G)FF3
        ///682)PLS
        ///91Z)DNX
        ///WKK)JWP
        ///FF3)F32
        ///CGL)F92
        ///YCF)8XZ
        ///VKQ)J6C
        ///DP4)6JF
        ///DWB)5RF
        ///5TG)WRP
        ///LWN)N2C
        ///5QB)34Z
        ///LK9)FB9
        ///VK9)WQM
        ///PLR)DP7
        ///BLV)KL4
        ///2XT)R7V
        ///CP3)TJT        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D06_Puzzle {
            get {
                return ResourceManager.GetString("D06_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,8,1001,8,10,8,105,1,0,0,21,46,59,80,105,122,203,284,365,446,99999,3,9,102,3,9,9,1001,9,5,9,102,2,9,9,1001,9,3,9,102,4,9,9,4,9,99,3,9,1002,9,2,9,101,2,9,9,4,9,99,3,9,101,5,9,9,1002,9,3,9,1001,9,3,9,1002,9,2,9,4,9,99,3,9,1002,9,4,9,1001,9,2,9,102,4,9,9,101,3,9,9,102,2,9,9,4,9,99,3,9,102,5,9,9,101,4,9,9,102,3,9,9,4,9,99,3,9,1002,9,2,9,4,9,3,9,101,1,9,9,4,9,3,9,1002,9,2,9,4,9,3,9,1001,9,2,9,4,9,3,9,1001,9,1,9,4,9,3,9,1001,9,1,9,4,9,3,9,1001,9,2,9,4,9,3,9,101,1,9,9,4,9,3,9,101,1,9,9,4,9,3,9,1001,9,1,9,4,9,99,3 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D07_Puzzle {
            get {
                return ResourceManager.GetString("D07_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22122222202222222222222202022222222202222001210200222022222222222222222222012220222202212222222222021222212222222222222222220222122222222210222221222222022222222222222222222222022222222202222022210212222022222222222222222222212221222212212222222222020222222222222222222222221222022222222200222222222222222222212222222222222212122222222222222001220222222122222222222222222222112221222212222222222222220222222222222222222222222222122222222200222220222222222202222222222222222222022212222212222120210211222222222222 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D08_Puzzle {
            get {
                return ResourceManager.GetString("D08_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1102,34463338,34463338,63,1007,63,34463338,63,1005,63,53,1102,1,3,1000,109,988,209,12,9,1000,209,6,209,3,203,0,1008,1000,1,63,1005,63,65,1008,1000,2,63,1005,63,904,1008,1000,0,63,1005,63,58,4,25,104,0,99,4,0,104,0,99,4,17,104,0,99,0,0,1102,1,1,1021,1101,0,21,1009,1101,0,28,1005,1102,1,27,1015,1102,39,1,1016,1102,1,30,1003,1102,25,1,1007,1102,195,1,1028,1101,0,29,1010,1102,26,1,1004,1102,1,555,1024,1102,32,1,1014,1101,0,23,1019,1102,1,31,1008,1101,652,0,1023,1102,20,1,1000,1101,0,821,1026,1102,814,1,1027,110 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D09_Puzzle {
            get {
                return ResourceManager.GetString("D09_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#..#{0}.....{0}#####{0}....#{0}...##.
        /// </summary>
        public static string D10_E1 {
            get {
                return ResourceManager.GetString("D10_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ......#.#.{0}#..#.#....{0}..#######.{0}.#.#.###..{0}.#..#.....{0}..#....#.#{0}#..#....#.{0}.##.#..###{0}##...#..#.{0}.#....####.
        /// </summary>
        public static string D10_E2 {
            get {
                return ResourceManager.GetString("D10_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #.#...#.#.{0}.###....#.{0}.#....#...{0}##.#.#.#.#{0}....#.#.#.{0}.##..###.#{0}..#...##..{0}..##....##{0}......#...{0}.####.###..
        /// </summary>
        public static string D10_E3 {
            get {
                return ResourceManager.GetString("D10_E3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#..#..###{0}####.###.#{0}....###.#.{0}..###.##.#{0}##.##.#.#.{0}....###..#{0}..#.#..#.#{0}#..#.#.###{0}.##...##.#{0}.....#.#...
        /// </summary>
        public static string D10_E4 {
            get {
                return ResourceManager.GetString("D10_E4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .#..##.###...#######{0}##.############..##.{0}.#.######.########.#{0}.###.#######.####.#.{0}#####.##.#.##.###.##{0}..#####..#.#########{0}####################{0}#.####....###.#.#.##{0}##.#################{0}#####.##.###..####..{0}..######..##.#######{0}####.##.####...##..#{0}.#####..#.######.###{0}##...#.##########...{0}#.##########.#######{0}.####.#.###.###.#.##{0}....##.##.###..#####{0}.#.#.###########.###{0}#.#.#.#####.####.###{0}###.##.####.##.#..##.
        /// </summary>
        public static string D10_E5 {
            get {
                return ResourceManager.GetString("D10_E5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##.###.#.......#.#....#....#..........#.
        ///....#..#..#.....#.##.............#......
        ///...#.#..###..#..#.....#........#......#.
        ///#......#.....#.##.#.##.##...#...#......#
        ///.............#....#.....#.#......#.#....
        ///..##.....#..#..#.#.#....##.......#.....#
        ///.#........#...#...#.#.....#.....#.#..#.#
        ///...#...........#....#..#.#..#...##.#.#..
        ///#.##.#.#...#..#...........#..........#..
        ///........#.#..#..##.#.##......##.........
        ///................#.##.#....##.......#....
        ///#............#.........###...#...#.....#
        ///#....#.. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D10_Puzzle {
            get {
                return ResourceManager.GetString("D10_Puzzle", resourceCulture);
            }
        }
    }
}
