//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeTests.Resources.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example1.
        /// </summary>
        public static string D00_E1 {
            get {
                return ResourceManager.GetString("D00_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example2.
        /// </summary>
        public static string D00_E2 {
            get {
                return ResourceManager.GetString("D00_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Puzzle.
        /// </summary>
        public static string D00_Puzzle {
            get {
                return ResourceManager.GetString("D00_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54172
        ///58469
        ///92948
        ///143402
        ///57563
        ///54532
        ///68042
        ///89847
        ///70872
        ///54069
        ///107310
        ///146439
        ///88851
        ///142869
        ///71309
        ///89613
        ///70338
        ///87708
        ///95305
        ///134384
        ///128250
        ///134991
        ///91270
        ///127819
        ///68650
        ///102556
        ///129882
        ///68688
        ///129939
        ///137344
        ///102624
        ///90828
        ///86487
        ///91712
        ///114866
        ///75697
        ///107599
        ///99053
        ///87511
        ///128128
        ///57772
        ///69314
        ///90771
        ///145376
        ///100730
        ///142675
        ///112731
        ///83985
        ///123565
        ///127325
        ///86597
        ///121772
        ///131992
        ///148859
        ///93348
        ///77294
        ///119763
        ///74636
        ///95592
        ///79628
        ///78861
        ///68565
        ///88820
        ///134291
        ///69262
        ///128678
        ///118216
        ///52799
        ///92731
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D01_Puzzle {
            get {
                return ResourceManager.GetString("D01_Puzzle", resourceCulture);
            }
        }
    }
}
