//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCodeTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Input {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Input() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCodeTests.Resources.Input", typeof(Input).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example1.
        /// </summary>
        public static string D00_E1 {
            get {
                return ResourceManager.GetString("D00_E1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Example2.
        /// </summary>
        public static string D00_E2 {
            get {
                return ResourceManager.GetString("D00_E2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day00_Puzzle.
        /// </summary>
        public static string D00_Puzzle {
            get {
                return ResourceManager.GetString("D00_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 54172
        ///58469
        ///92948
        ///143402
        ///57563
        ///54532
        ///68042
        ///89847
        ///70872
        ///54069
        ///107310
        ///146439
        ///88851
        ///142869
        ///71309
        ///89613
        ///70338
        ///87708
        ///95305
        ///134384
        ///128250
        ///134991
        ///91270
        ///127819
        ///68650
        ///102556
        ///129882
        ///68688
        ///129939
        ///137344
        ///102624
        ///90828
        ///86487
        ///91712
        ///114866
        ///75697
        ///107599
        ///99053
        ///87511
        ///128128
        ///57772
        ///69314
        ///90771
        ///145376
        ///100730
        ///142675
        ///112731
        ///83985
        ///123565
        ///127325
        ///86597
        ///121772
        ///131992
        ///148859
        ///93348
        ///77294
        ///119763
        ///74636
        ///95592
        ///79628
        ///78861
        ///68565
        ///88820
        ///134291
        ///69262
        ///128678
        ///118216
        ///52799
        ///92731
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D01_Puzzle {
            get {
                return ResourceManager.GetString("D01_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,0,0,3,1,1,2,3,1,3,4,3,1,5,0,3,2,13,1,19,1,9,19,23,2,23,13,27,1,27,9,31,2,31,6,35,1,5,35,39,1,10,39,43,2,43,6,47,1,10,47,51,2,6,51,55,1,5,55,59,1,59,9,63,1,13,63,67,2,6,67,71,1,5,71,75,2,6,75,79,2,79,6,83,1,13,83,87,1,9,87,91,1,9,91,95,1,5,95,99,1,5,99,103,2,13,103,107,1,6,107,111,1,9,111,115,2,6,115,119,1,13,119,123,1,123,6,127,1,127,5,131,2,10,131,135,2,135,10,139,1,13,139,143,1,10,143,147,1,2,147,151,1,6,151,0,99,2,14,0,0.
        /// </summary>
        public static string D02_Puzzle {
            get {
                return ResourceManager.GetString("D02_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R991,U77,L916,D26,R424,D739,L558,D439,R636,U616,L364,D653,R546,U909,L66,D472,R341,U906,L37,D360,L369,D451,L649,D521,R2,U491,R409,U801,R23,U323,L209,U171,L849,D891,L854,U224,R476,D519,L937,U345,R722,D785,L312,D949,R124,U20,R677,D236,R820,D320,L549,D631,R42,U621,R760,U958,L925,U84,R914,U656,R598,D610,R397,D753,L109,U988,R435,U828,R219,U583,L317,D520,L940,D850,R594,D801,L422,U292,R883,U204,L76,U860,L753,U483,L183,U179,R441,U163,L859,U437,L485,D239,R454,D940,R689,D704,R110,D12,R370,D413,L192,D979,R990,D651,L308 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D03_Puzzle {
            get {
                return ResourceManager.GetString("D03_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 124075-580769.
        /// </summary>
        public static string D04_Puzzle {
            get {
                return ResourceManager.GetString("D04_Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3,225,1,225,6,6,1100,1,238,225,104,0,1102,31,68,225,1001,13,87,224,1001,224,-118,224,4,224,102,8,223,223,1001,224,7,224,1,223,224,223,1,174,110,224,1001,224,-46,224,4,224,102,8,223,223,101,2,224,224,1,223,224,223,1101,13,60,224,101,-73,224,224,4,224,102,8,223,223,101,6,224,224,1,224,223,223,1101,87,72,225,101,47,84,224,101,-119,224,224,4,224,1002,223,8,223,1001,224,6,224,1,223,224,223,1101,76,31,225,1102,60,43,225,1102,45,31,225,1102,63,9,225,2,170,122,224,1001,224,-486,224,4,224,102,8,223,223,101,2,224,224 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string D05_Puzzle {
            get {
                return ResourceManager.GetString("D05_Puzzle", resourceCulture);
            }
        }
    }
}
